name: Scheduled Review Analysis

on:
  schedule:
    - cron: '*/10 * * * *'  # Runs every 10 minutes
  workflow_dispatch:        # Allows manual trigger

jobs:
  run-analysis:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install spacy metaphone jellyfish rapidfuzz sentence-transformers xlsxwriter
          python -m spacy download en_core_web_trf

      - name: Run analysis script
        run: python run_analysis.py

      - name: Upload Excel output
        uses: actions/upload-artifact@v3
        with:
          name: final-output
          path: final_output.xlsx
