name: Run Analysis and Upload Results

on:
  schedule:
    - cron: '*/10 * * * *'  # every 10 minutes
  workflow_dispatch:        # manual trigger

jobs:
  run-analysis:
    runs-on: ubuntu-22.04

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python 3.11
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run analysis script
        run: |
          python run_analysis.py

      - name: Upload output artifacts
        uses: actions/upload-artifact@v2
        with:
          name: analysis-results
          path: ./output/
