# .github/workflows/run-analysis.yml

name: Run Analysis and Upload Results

on:
  schedule:
    - cron: '*/10 * * * *'  # Every 10 minutes
  workflow_dispatch:        # Manual run support

jobs:
  run-analysis:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run script
        run: |
          python run_analysis.py

      - name: Upload output
        uses: actions/upload-artifact@v3.1.3
        with:
          name: output
          path: ./output/
